[package]
name = "sandbox-app-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
egui = "0.29"
epaint = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1.19"
libc = "0.2"
