[package]
name = "file-explorer"
version.workspace = true
edition.workspace = true

autobins = false

[[bin]]
name = "file_explorer"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.33", default-features = false, features = ["x11", "default_fonts", "glow"] }
